#!/usr/bin/env python3
import subprocess
import sys

for i in sys.argv[1:]:
    name,ext = os.path.splitext(i)
    
    image_file = open(i,"rb")
    crc_file = open(name+"_crc"+ext,"wb")

    print("generating", name+"_crc"+ext, "...")

    while buf := image_file.read(32768):
        crc = subprocess.check_output(["./crc16"], input=buf)
        crc = bytes.fromhex(crc.decode())
        crc = bytes([crc[1], crc[0]])
        crc_file.write(crc)

    crc_file.close()
    image_file.close()
