#!/usr/bin/env python3
import os
import sys
import libscrc
import math

for i in sys.argv[1:]:
    name,ext = os.path.splitext(i)
    
    image_file = open(i,"rb")
    crc_file = open(name+"_crc32c"+ext,"wb")

    print("generating", name+"_crc32c"+ext, "...")

    size = os.path.getsize(i)
    
    crc_file.write(b"\x41\x6f\xdc\x1e\x18\x00\x00\x00") # magic
    crc_file.write((size - 28).to_bytes(4, byteorder="little"))
    crc_file.write(b"\x00\x00\x00\x00")
    crc_file.write(b"\xc6\x18\xf3\xe9") # mutable magic, must be known
    crc_file.write((math.ceil(size / (65536)) * 4 + 24).to_bytes(4, byteorder="little"))

    while buf := image_file.read(65536):
        buf += b"\x00" * (65536 - len(buf))
        crc_file.write(libscrc.crc32_c(buf).to_bytes(4, byteorder="little"))

    crc_file.close()
    image_file.close()
